### ISSUE TITLE
Cloudflare CPU 时间

### ISSUE THREAD

**Issue by yy4382** [yy4382/read-aloud#2]
https://github.com/yy4382/read-aloud/issues/1#issuecomment-2507445424

Cloudflare Worker CPU 时间超限问题，可能超过 Cloudflare Workers 的10ms限额

@DomKing 可以截张这个界面的图吗

![CleanShot_2024-12-02_14 22 12](https://github.com/user-attachments/assets/4a47aa96-7271-4326-ae40-d28a2d2cc5e9)

**Comment by yy4382** [comment]
目前来看我觉得实在没有什么可以优化的地方了，（至少从我自己 Profiling的结果来看）大部分的开销都来自 WebSocket 内部实现读取音频二进制数据。

由于 Cloudflare 是按每次请求计算 CPU 时间的，可以尝试降低每次请求合成的字符数（爱阅记和爱阅书香可以配置，其他应用不清楚）。在我的测试中，如果每次合成100字，在默认音质下中位数5ms，99% 10ms。使用比较差的音质应该也有帮助，但还没测试。

**Comment by yy4382** [comment]
测试结果：100字，音质 audio-24khz-48kbitrate-mono-mp3，在一个只有我在用的实例上
<img width="740" alt="image" src="https://github.com/user-attachments/assets/887c57b7-98ad-4ead-a451-586757736ec9">

**Comment by yy4382** [comment]
@DomKing 能问下你用的哪个阅读器吗？大概每次合成会合成多少字？

因为我部署的实例还从来没有出现过 CPU 时间超限的问题，它应该主要是爱阅书香用户在用，每次最大合成200字

**Comment by DomKing** [comment]
> [#1 (comment)](https://github.com/yy4382/read-aloud/issues/1#issuecomment-2507445424)
> 
> Cloudflare Worker CPU 时间超限问题，可能超过 Cloudflare Workers 的10ms限额
> 
> @DomKing 可以截张这个界面的图吗
> 
> ![CleanShot_2024-12-02_14 22 12](https://private-user-images.githubusercontent.com/55980292/391735225-4a47aa96-7271-4326-ae40-d28a2d2cc5e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTQ0ODQsIm5iZiI6MTczMzE5NDE4NCwicGF0aCI6Ii81NTk4MDI5Mi8zOTE3MzUyMjUtNGE0N2FhOTYtNzI3MS00MzI2LWFlNDAtZDI4YTJkMmNjNWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDAyNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjkyNzYzNmRkOWM1ZWQ0NWIzNTQ1NDMzZDU0ZmE2ODFhMDE2MWFmNTVjZjVhYTBkNWQ2MzZiM2YxZWVmNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fbHZ0MXz6IbvJGkSXQ2xEjMU53q1uHnRagLjE2tt4To)

我用的爱阅记，合成200字。根据日志看，也是在处理ws返回的音频过程中超时。
你的截图显示有5个错误请求，你可以点开看下，应该也是超出cpu time.

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/c48e33e6-2e8c-44fd-ac21-7f00c0a7acf8">

**Comment by yy4382** [comment]
> > [#1 (comment)](https://github.com/yy4382/read-aloud/issues/1#issuecomment-2507445424)
> > Cloudflare Worker CPU 时间超限问题，可能超过 Cloudflare Workers 的10ms限额
> > @DomKing 可以截张这个界面的图吗
> > ![CleanShot_2024-12-02_14 22 12](https://private-user-images.githubusercontent.com/55980292/391735225-4a47aa96-7271-4326-ae40-d28a2d2cc5e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxOTQ0ODQsIm5iZiI6MTczMzE5NDE4NCwicGF0aCI6Ii81NTk4MDI5Mi8zOTE3MzUyMjUtNGE0N2FhOTYtNzI3MS00MzI2LWFlNDAtZDI4YTJkMmNjNWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDAyNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMjkyNzYzNmRkOWM1ZWQ0NWIzNTQ1NDMzZDU0ZmE2ODFhMDE2MWFmNTVjZjVhYTBkNWQ2MzZiM2YxZWVmNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fbHZ0MXz6IbvJGkSXQ2xEjMU53q1uHnRagLjE2tt4To)
> 
> 我用的爱阅记，合成200字。根据日志看，也是在处理ws返回的音频过程中超时。 你的截图显示有5个错误请求，你可以点开看下，应该也是超出cpu time.
> 
> <img alt="image" width="1033" src="https://private-user-images.githubusercontent.com/7285294/391790411-c48e33e6-2e8c-44fd-ac21-7f00c0a7acf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDA2NjQsIm5iZiI6MTczMzIwMDM2NCwicGF0aCI6Ii83Mjg1Mjk0LzM5MTc5MDQxMS1jNDhlMzNlNi0yZThjLTQ0ZmQtYWMyMS03ZjAwYzBhN2FjZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMDQzMjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM5MDNkZWFjZGUzMDZjMGZmNWNlYzcxODI4NTkwOGMwMDhiNjAyZDZkOWFlZTNhNTdmYmZhZGQ5ZWM3ZTk4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xuyf4ZQmaCFEsXeKI1hlNX6bFnNw6EF5HDWk4PTZBN4">

我的自从三天前那次优化之后就再也没出过 CPU limit 类型的错误了，你试试把字数设成 150 或者 100，看看有没有改善

**Comment by yy4382** [comment]
感谢支持！
